# This is a basic workflow to help you get started with Actions

name: GitHub Actions Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 6 * * 0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
     environment:
       description: 'Environment to deploy to'
       type: environment
       required: true
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    name: Build Demo
    # The type of runner that the job will run on
    runs-on: ubuntu-latestt
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo " The job was triggered by event: ${{ github.event_name }}"
          echo " The name of your branch is ${{ github.ref }} and your repository is."
 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files"

  Test:
    runs-on: ubuntu-latestt
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "testing..."

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo: " Testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: ['Test', 'Load-Test']
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Configure Production'
    steps:
      - run: |
          echo: "In Production"
          
